### ISSUE TITLE
When I try to integrate, give me this error.

### ISSUE THREAD

**Issue by 0xrafasec** [n3wc/titapjoy_ios#1]
*\* BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :   Ld build/Debug-iphonesimulator/MyApp.app/MyApp normal i386
[ERROR] :  (1 failure)

**Comment by n3wc** [comment]
sorry, forgot to update the module to properly include TapjoyResources.bundle i need to get that fixed!
in the mean time you can grab it from https://github.com/n3wc/titapjoy_ios/tree/master/assets and place in your app/assets/iphone folder.

**Comment by 0xrafasec** [comment]
Hey, just to share with you...I developed my version too.
https://github.com/rafagomes/titanium-tap-joy
